[vars]
ruff_check_cmd = 'poetry run ruff check'

[tasks]
setup = "poetry install"
lint = '{{vars.ruff_check_cmd}}'
fix = '{{vars.ruff_check_cmd}} --fix'
test = "poetry run pytest"
local_ci = 'act'

[tasks.build]
depends = ['lint', 'test']

[tasks.ci]
depends = ['setup']
run = 'mise build' # Adding to depends would make it run before setup finishes

[tools]
act = "latest"
poetry = "latest"
python = "latest"
