[vars]
poetry_run_prefix = 'poetry run'
ruff_check_prefix = '{{vars.poetry_run_prefix}} ruff check'

[tasks]
lint = '{{vars.ruff_check_prefix}}'
fix = '{{vars.ruff_check_prefix}} --fix'

setup = "poetry install"
test = "{{vars.poetry_run_prefix}} pytest"
local_ci = 'act'

[tasks.build]
depends = ['lint', 'test']

[tasks.ci]
depends = ['setup']
run = 'mise build' # Adding to depends could make it run before setup finishes

[tools]
act = "latest"
poetry = "latest"
python = "latest"
